jest.autoMockOff();
const defineTest = require('jscodeshift/dist/testUtils').defineTest;

defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'function-anonymous', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true }, 'function-anonymous-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'function-arrow', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true }, 'function-arrow-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'function-declaration', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'function-declaration-export-default-function', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true }, 'function-declaration-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true }, 'function-rest-parameter', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'function-return', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'method-constructor', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params': true }, 'method-constructor-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params': true }, 'method-constructor-logparams-access-modifier', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'method-instance', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true}, 'method-instance-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'method-static', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'params' : true }, 'method-static-logparams', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__'}, 'statement-expression', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'rxjs' : true }, 'rxjs-basic', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'rxjs' : true }, 'rxjs-basic-existing-tap-import', { 'parser': 'ts' });
defineTest(__dirname + '../', 'transform', {'relpath': '__testfixtures__', 'rxjs' : true } , 'rxjs-internal-tap-import', { 'parser': 'ts' });
